version: '3.4'

services:
  api:
    image: yourdockerhubusername/instructo-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=tcp:instructo-server.database.windows.net,1433;Initial Catalog=instructo;User ID=ironman;Password=YOUR_PASSWORD;